services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: devPilot-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: devPilot
      POSTGRES_DB: devPilot
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5